# Generated by Django 3.0 on 2020-02-15 14:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0020_auto_20200215_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='typology',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
