# Generated by Django 3.0 on 2020-02-15 14:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0021_auto_20200215_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='language',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
