# Generated by Django 3.0 on 2020-02-15 14:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0022_auto_20200215_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='language',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=11, size=1),
        ),
    ]
