# Generated by Django 3.0 on 2020-02-13 22:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('detailPageName', models.CharField(max_length=100)),
                ('portID', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=30)),
                ('typology', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=22, size=2)),
                ('activityLevel', models.CharField(max_length=30)),
                ('collectionType', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=200)),
                ('language', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=10, size=1)),
                ('priceLevel', models.IntegerField()),
                ('currency', models.CharField(max_length=8)),
                ('mealInfo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('shortDescription', models.CharField(max_length=8)),
                ('longDescription', models.CharField(max_length=200)),
                ('externalContent', models.BooleanField()),
                ('minimumAge', models.CharField(max_length=3)),
                ('wheelChairAccessible', models.BooleanField()),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
