# Generated by Django 3.0 on 2020-02-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0002_auto_20200214_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='longDescription',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursion',
            name='mealInfo',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursion',
            name='minimumAge',
            field=models.CharField(default='null', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursion',
            name='shortDescription',
            field=models.CharField(default='null', max_length=8),
            preserve_default=False,
        ),
    ]
