# Generated by Django 3.0 on 2020-02-15 04:29

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0003_auto_20200214_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='typology',
            field=django_mysql.models.ListCharField(models.IntegerField(), max_length=22, size=2),
        ),
    ]
