# Generated by Django 3.0 on 2020-02-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0005_auto_20200214_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='longDescription',
            field=models.CharField(max_length=10000),
        ),
    ]
