# Generated by Django 3.0 on 2020-02-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0007_auto_20200214_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='longDescription',
            field=models.CharField(default='null', max_length=10000),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='mealInfo',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='minimumAge',
            field=models.CharField(default='null', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='shortDescription',
            field=models.CharField(default='null', max_length=8),
        ),
    ]
