# Generated by Django 3.0 on 2020-02-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0008_auto_20200214_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='minimumAge',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
