# Generated by Django 3.0 on 2020-02-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0012_auto_20200214_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='typology',
            field=models.IntegerField(),
        ),
    ]
