# Generated by Django 3.0 on 2020-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0018_auto_20200215_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='language',
        ),
        migrations.AddField(
            model_name='excursion',
            name='language',
            field=models.TextField(default='[]'),
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='typology',
        ),
        migrations.AddField(
            model_name='excursion',
            name='typology',
            field=models.TextField(default='[]'),
        ),
    ]
