# Generated by Django 3.0 on 2020-02-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0026_auto_20200215_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
